image: Ubuntu

stack: jdk 11  # версия JDK

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifact/app-order.jar &

build_script:
  - ./gradlew test --info "-Dselenide.headless=true"
